// This file is automatically generated. Do not modify it manually.
// You can publish a new configuration by running "firebase apps:sdkconfig"
// from the Firebase CLI.
//
// Note: This object is safe to commit to version control

export const firebaseConfig = {
  "projectId": "staffwise-app",
  "appId": "1:1025595568434:web:865d1cf37976193de33f54",
  "storageBucket": "staffwise-app.appspot.com",
  "apiKey": process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
  "authDomain": "staffwise-app.firebaseapp.com",
  "messagingSenderId": "1025595568434",
  "measurementId": "G-5YJ022C0S2"
};
